// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjr0eqOlhkm3X35Y6Ir1wHudlnQcnjEPE',
    appId: '1:749268725625:web:6cac924cc5573bd88a09a8',
    messagingSenderId: '749268725625',
    projectId: 'athidihub',
    authDomain: 'athidihub.firebaseapp.com',
    storageBucket: 'athidihub.firebasestorage.app',
    measurementId: 'G-FBV89SP8HP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd1dnxBlNgxxSgb3TsgavEQD7MRz6oVak',
    appId: '1:749268725625:android:3f352ce8309495598a09a8',
    messagingSenderId: '749268725625',
    projectId: 'athidihub',
    storageBucket: 'athidihub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACtln0Uz6V4UNd7xnmI0Lo7E8Wy4RgPLY',
    appId: '1:749268725625:ios:31d45ee636e1be218a09a8',
    messagingSenderId: '749268725625',
    projectId: 'athidihub',
    storageBucket: 'athidihub.firebasestorage.app',
    iosBundleId: 'com.athidihub.athidihub',
  );
}
